/homes/ss5921/Dissertation/drone_attack_sim/gym-pybullet-drones/gym-pybullet-drones/gym_pybullet_drones/envs/BaseAviary.py:7: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
pybullet build time: Jun 27 2025 13:59:41
/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/gymnasium/core.py:311: UserWarning: [33mWARN: env.increase_difficulty to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.increase_difficulty` for environment variables or `env.get_wrapper_attr('increase_difficulty')` that will search the reminding wrappers.[0m
  logger.warn(
Traceback (most recent call last):
  File "/homes/ss5921/Dissertation/drone_attack_sim/agents/train_sac.py", line 759, in <module>
    train_progressive_drone_navigation()
  File "/homes/ss5921/Dissertation/drone_attack_sim/agents/train_sac.py", line 736, in train_progressive_drone_navigation
    model.learn(
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/stable_baselines3/sac/sac.py", line 308, in learn
    return super().learn(
           ^^^^^^^^^^^^^^
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 328, in learn
    rollout = self.collect_rollouts(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 560, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(actions)
                                     ^^^^^^^^^^^^^^^^^
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 222, in step
    return self.step_wait()
           ^^^^^^^^^^^^^^^^
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/stable_baselines3/common/vec_env/vec_normalize.py", line 181, in step_wait
    obs, rewards, dones, infos = self.venv.step_wait()
                                 ^^^^^^^^^^^^^^^^^^^^^
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 71, in step_wait
    obs, self.reset_infos[env_idx] = self.envs[env_idx].reset()
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/stable_baselines3/common/monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/stable_baselines3/common/monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homes/ss5921/Dissertation/drone_attack_sim/agents/train_sac.py", line 187, in reset
    self._generate_progressive_obstacles()
  File "/homes/ss5921/Dissertation/drone_attack_sim/agents/train_sac.py", line 411, in _generate_progressive_obstacles
    required_clearance = [0.0, 1.2, 1.0, 0.8][self.difficulty_level]
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
Exception ignored in: <function tqdm.__del__ at 0x7d999e400b80>
Traceback (most recent call last):
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/tqdm/std.py", line 1148, in __del__
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/tqdm/rich.py", line 121, in close
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/rich/progress.py", line 1191, in __exit__
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/rich/progress.py", line 1177, in stop
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/rich/live.py", line 150, in stop
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/rich/live.py", line 247, in refresh
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/rich/console.py", line 1693, in print
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/rich/console.py", line 1550, in _collect_renderables
  File "/vol/bitbucket/ss5921/drone_venv/lib/python3.12/site-packages/rich/protocol.py", line 28, in rich_cast
ImportError: sys.meta_path is None, Python is likely shutting down
